### ISSUE TITLE
Checklist/quickstart guide for responsible repo management

### ISSUE THREAD

**Issue by arex1337** [vismagroup/visma-oss-contribution-model#11]
Examples:

- [ ] Having a README.md
- [ ] .gitignore
- [ ] .gitattributes
- [ ] Publicly available CI
- [ ] CONTRIBUTING.md
- [ ] CODEOFCONDUCT.md
- [ ] Usage of GitHub labels
- [ ] git history management
- [ ] No secrets or other content that should not be public
- [ ] Leverage built-in security tooling (e.g. dependabot, CodeQL)
